exports.INITIAL_EVENT = {
  brand_id: '',
  eventMediaUrl: 'placeholder',
  adminMediaUrl:
    'https://res.cloudinary.com/brand-socialite/image/upload/v1596733183/michel-stockman-yh5hjDZW_no-unsplash_s7g1fo.jpg',
  eventName: '',
  hostName: '',
  eventType: '',
  estAttendance: '',
  date: '',
  setupStart: '',
  setupEnd: '',
  eventStart: '',
  eventEnd: '',
  breakdownStart: '',
  breakdownEnd: '',
  venue: '',
  address1: '',
  address2: '',
  city: '',
  state: '',
  zip: '',
  parking: '',
  parkingvenue: '',
  parkingvenue: '',
  parkingaddress1: '',
  parkingaddress2: '',
  parkingcity: '',
  parkingstate: '',
  parkingzip: '',
  parkingInstructions: '',
  uniforms: '',
  uniformsInstructions: ''
};
